services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: >
      sh -c "python scripts/make_sample_data.py && python -m pipeline.main"

  dry-run:
    extends: pipeline
    command: >
      sh -c "python scripts/make_sample_data.py && python -m pipeline.main --dry-run"

  tests:
    extends: pipeline
    command: pytest -v
