services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python -m pipeline.main

  test:
    build: .
    command: pytest -v
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
