services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python -m pipeline.main

  make-data:
    extends: pipeline
    command: python scripts/make_sample_data.py

  dry-run:
    extends: pipeline
    command: python -m pipeline.main --dry-run

  tests:
    extends: pipeline
    command: pytest -v
