name: Full Run

on:
  schedule:
    - cron: '0 23 * * 0'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ETL pipeline
        run: docker compose run --rm pipeline
      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-outputs
          path: |
            data/*.csv
            logs/*.log
