name: Integration Tests

on: workflow_dispatch

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: docker-compose run --rm tests pytest -m integration -v
